Litefs world db
The-Overlore/lore-machine pull request #11
Opened 2024-01-12 05:54 UTC by jobez

currently a draft because i had to hack some changes just to sanity check that litefs was correctly configured, will comment out what are temporary and will be lined up before taking out of draft

2024-01-12 05:59 UTC, jobez reviewed
initial explanatory review

2024-01-12 05:59 UTC, jobez commented on overlore/townhall/service.py
> +import sqlean
temporarily connecting/querying world db in the entry point for debug convenience, can remove and add something simple that can be iterated on in a subsequent PR

2024-01-12 05:59 UTC, jobez commented on overlore/townhall/service.py
> +    DatabaseHandler.instance().init()
some changes were done by the linter in response to me commenting out code, in particular the removal of assignments

2024-01-12 05:59 UTC, jobez commented on overlore/townhall/service.py
> +    while True:
there was an issue with reliably establishing web socket connections, so I commented them out. then with those commented out, the overlore_pulse service wouldn't block on the gather call, so the program would just terminate on start.

that's why, temporarily, i commented it out and just put a while true loop and queried the world.db that the litefs service is meant to sync

2024-01-12 05:59 UTC, jobez commented on overlore/townhall/service.py
> +    print("wtf")
added this to sanity check that the program was just exiting early when the service stuff was started from docker. its possible whats happening is that an error is being thrown, but it isn't being logged correctly.

2024-01-15 10:37 UTC, edisontim commented
The way it connects looks really clean

2024-01-23 09:33 UTC, edisontim requested changes
Could you add something in the readme.md about the world_db pls?

2024-01-23 17:54 UTC, jobez commented
> Could you add something in the readme.md about the world_db pls?

Would be easier when we merge the docker compose changes, so I can link out to it in the docker system files in eternums. Will just link out to it assuming those changes will get merged.

2024-01-23 20:21 UTC, edisontim approved these changes

2024-01-23 20:21 UTC, merged