feat: change storing of realm_entity_id to realm_id + add subscription to the SpawnNpc event
The-Overlore/lore-machine pull request #68
Opened 2024-02-21 09:21 UTC by edisontim

Positions and names of the realms are determined by the `realm_id` and not the `realm_entity_id`. Adds the `realm_id` via the  PR and stores is in this PR.

PR also includes the subscription to the `SpawnNpc` event

Refactored a few things as well 😬

2024-02-21 15:01 UTC, cwastche requested changes
Found a breaking bug in file overlore/llm/natural_language_formatter.py
Function _order_accepted_to_nl()
Line 57 : """metadata: dict[Any, Any] = str_to_json(str(event[6]))"""
Metadata was pushed back to the 8th index.

2024-02-21 15:19 UTC, cwastche commented on overlore/townhall/service.py
> +    await torii_boot_sync(config.env["TORII_GRAPHQL"])
torii_boot_sync before launching prompt_loop

2024-02-22 18:11 UTC, edisontim commented
> Found a breaking bug in file overlore/llm/natural_language_formatter.py Function _order_accepted_to_nl() Line 57 : """metadata: dict[Any, Any] = str_to_json(str(event[6]))""" Metadata was pushed back to the 8th index.
> 
> Same for _combat_outcome_to_nl() Line 34

Fixed in my latest commit

2024-02-22 21:28 UTC, cwastche commented on overlore/townhall/service.py
>          msg = f'{{"realm_id": {realm_id}, "order": 1}}'
change "order" to "orderId" as per your latest commit

2024-02-22 21:29 UTC, cwastche approved these changes
Lgtm, small typo in prompt_loop that needs to change

2024-02-23 11:53 UTC, cwastche approved these changes
Lgtm, mergeable

2024-02-23 12:47 UTC, merged